### ISSUE TITLE
Bug? with answer matching

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#10]
What just happened???
<img width="746" alt="Screenshot 2023-12-08 070957" src="https://github.com/scott2000/answerset/assets/51899303/758eaac6-9acb-4d62-88fd-2b1dbcd76dca">

Ah. For some reason it matched the e to Xen first, which was a separate answer because of the comma.
<img width="784" alt="Screenshot 2023-12-08 071021" src="https://github.com/scott2000/answerset/assets/51899303/b5bbb86c-e119-4a8a-92f7-c7ef5acfcd78">

I think I'm okay with how the comma splits that into separate answers at all there, the Norwegian part. That's, well, not wrong actually. ...Though having it keep stuff in brackets together might be nice? I can also see that breaking things for the user though; no, explicitly Not asking for anything to be changed *there*. At least for now...

But what I do dislike, is that it did not detect kler på meg as a correct answer. It should have, shouldn't it?

**Comment by scott2000** [comment]
Ok, I think it should be fixed now. I changed it so that it sees:

* `kler på meg` has 1 letter correct when compared to `Xen`.
* `kler på meg` has 9 letters correct when compared to `kler på meg/deg/seg/oss`.

So it will match it the option with the most correct letters. Basically instead of minimizing wrong/missing letters, it will try to maximize correct letters, which I think should be more intuitive and give better results. I'm still thinking about adding a configuration option to ignore commas inside of brackets, so I'll let you know if/when I add that. Let me know if you see any other issues!

**Comment by scott2000** [comment]
Now I updated the add-on to not split on commas inside of parentheses/brackets:

<img width="429" alt="2023-12-11" src="https://github.com/scott2000/answerset/assets/5590720/936d8d27-d08f-4a06-bac5-9ce70af27b14">

This is controllable by a configuration option though, so it can be disabled if it breaks anything. The commas are still treated as required though, so that is why it is reported as an error to leave out `Xen` here for instance. I don't really see any easy way to fix that, so I'd recommend to write `kler på (meg/deg/seg/oss/Xen)` instead.

**Comment by DianeNox** [comment]
yeah, I updated that card a long while ago. I split it into "kler på (meg/deg...), kler på Xen." instead.

Thanks a bunch for always reacting to anything I report so quickly!

**Comment by scott2000** [comment]
No problem! :)
