### ISSUE TITLE
another bug with / and or double brackets?

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#16]
<img width="437" alt="Screenshot 2024-01-05 144352" src="https://github.com/scott2000/answerset/assets/51899303/b2d5028b-ec19-4a17-85d4-9ca7b2109fe2">

Hello again... Yeah, really not much to say this time. Another bug like that. I'm really confused by this one tbh.

**Comment by scott2000** [comment]
Hmm let me take a look. I think it may have been something broken by the last change I made.

**Comment by scott2000** [comment]
I think it should be fixed now. I just redesigned the whole way it handles these, because there seemed to be lots of issues with the way I was doing it before. I'm hoping that this new implementation should work a lot better, especially when there's multiple optional things in a row. Let me know if you find anything else!

**Comment by DianeNox** [comment]
Thanks a bunch! I'll keep you updated if I encounter anything else!
