### ISSUE TITLE
How to deal with brackets

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#3]
<img width="440" alt="Screenshot 2023-11-13 184959" src="https://github.com/scott2000/answerset/assets/51899303/00a56f8e-d5bc-4dba-a957-c4310360d2d3">

Apologies for the mess that is me trying to create this issue. But anyway, here we go, finally. This kind of thing. I suppose the bracketed content at the end being excluded is actually intentional, for when there's annotations or such at the end? At least, if I remember correctly, this didn't occur when the bracketed text was at the beginning of the card. Maybe this could be a configurable option or something, whether to have bracketed content at the end of a card also included in checking or not??

**Comment by DianeNox** [comment]
Nevermind :D Your add-on's great, and the thing I wanted to comment on, after deactivating the add-on for a moment and going through my cards again, turns out that was just basic Anki and not your add-on at all. I don't think I even can delete this issue unfortunately, so just adding this comment as well I guess. Sorry? ^^'

**Comment by scott2000** [comment]
I updated the add-on so that parenthesized text isn't interpreted as a note if there isn't a space before it, and it should also not mark missing parenthesized text as incorrect now within an answer. If you open up the "Add-ons" menu in Anki and click "Check for Updates" and then restart Anki, it should work now. I marked this issue as closed, but if you see any issues with it, you can re-open it and I'll try to fix it.
