### ISSUE TITLE
correct answer not found again?

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#34]
Hello, me again... And, well, yeah. This issue has decided to pop up again, but seemingly only in specific conditions. I'm really not sure what's happening tbh.
<img width="1020" alt="Screenshot 2024-04-25 064433" src="https://github.com/scott2000/answerset/assets/51899303/513fcf9c-e592-4a62-92e0-85e7b08c18b1">

**Comment by scott2000** [comment]
I think what's going on is that when matching answers, it only tries to make sure that as many letters are correct as possible, and all 21 letters are correct for both options, so it basically picks one at random. I'll look into this and see if I can fix it.

**Comment by scott2000** [comment]
I updated it so that instead of just trying to maximize the number of correct characters and ignoring everything else, now it actually tries to give the best final difference (including minimizing the number of errors), so that should fix this issue and hopefully any similar issues! Let me know if you see any problems after the update.
